### ISSUE TITLE
Error: Print failed: Unknown

### ISSUE THREAD

**Issue by dasdirksche** [attah/harbour-seaprint#13]
Like described in the comments of the jolla store your app finally detected my printer. Only jpeg is possible. :(
But after choosing a picture and starting the print job I got the error: Print failed: Unknown

**Comment by attah** [comment]
I'm afraid i might have over-estimated what a printer claiming to be capable of JPEGs is able to handle. Need to look in to this further. Thanks for reporting!

**Comment by attah** [comment]
It seems at least someone was able to print a JPEG, so some printers do it.
The next release will include various improvements, including improved error messages.

**Comment by attah** [comment]
Hi!
In the recent versions of the app, jpeg resizing has been enabled. Did that help at all?
There are other improvements coming, but i'm seriously considering reverting jpeg resizing, so just checking if anyone is actually benefiting from it.
