### ISSUE TITLE
adding pdf functionality

### ISSUE THREAD

**Issue by teertinker** [attah/harbour-seaprint#34]
Hey,
first of all: a great app! Very useful and quite user friendly. I had a small issue that might be relevant for other users. The problem arose when I tried to print a pdf.

1. The explanation "In order to convert PDF files to other formats, you need utilities from the package \"poppler-utils\" was not self-explaining, because as a user I don't convert, but **print** a file. May be the phrase can be changed.
2. The cli commands could not be copied (e.g. pkcon install poppler-utils). This is not really a problem, but would make it easier for users.
3. The most serious problem arose after installing poppler utils: My network printer didn't show up afterwards - while it was previously working. A restart of the app didn't work. I had to restart the phone. Afterwards everything worked fine. May be a note could be added that a restart of the phone might be necessary. 

Thank you for your effort.

**Comment by attah** [comment]
1. Hmm, yes, it should probably be something more like "in order to convert PDF files to formats more likely to be accepted by most printers". Would that make sense? I do want to remain transparent to the end user with what is going on, but i also want to make it understandable... (This is as opposed to directly printing PDFs to printers that already supports it.)
2. I'll see what i can do.
3. Well, that is strictly impossible that it is closely related. The app can be flaky, the network subsystem of the phone can be flaky, and the printer can be flaky. But the app does not keep any state that could have been influenced by a phone restart and not a app restart. (and poppler-utils is nowhere near the discovery logic)

**Comment by attah** [comment]
Or maybe even "in order to enable PDF printing with printers that does not natively support it, you need poppler-utils to convert to formats they are more likely to accept"?

**Comment by attah** [comment]
How about this? e98002dad682755b476d3ebd0935e83ffe220383

**Comment by teertinker** [comment]
Thanks for the quick response: 
@1: I like your second suggestion. May be one could also rephrase it: "To enable PDF printing you may need poppler-utils to convert the files to formats more likely to be accepted by your printer"
@3 Well that's strange. After installation my printer showed up immediately. I even printed a picture. Than I installed poppler utils (while leaving the seaprint app open). After completion of installation the printer disappeared from the app. A restart of the app didn't change anything. A restart of the phone did.

**Comment by attah** [comment]
No worries. Thanks for the feedback. Did you check the commit i linked?

Regarding 3) odd, but SeaPrint only checks presence of poppler-utils at start of the app. The only thing that could have interfered with that is if you lost or changed wifi connectivity.

**Comment by teertinker** [comment]
I am no native speaker, but I would change your description a little bit (see comment above for an alternative description):
text: qsTr("In order to print PDF files with printers that **do** not support PDF natively,"
                       +" you nee**d t**he package \"poppler-utils\"."
                       +" This enables SeaPrint to convert to formats that **are more likely to be accepted."**)

**Comment by attah** [comment]
Good points, i have applied the edits. The first edit was especially educational. (:

**Comment by attah** [comment]
I have now added installation instructions for calligra(converter) to the NagScreen. It won't be available until, probably, Sailfish OS 4.2, but feel free to review the text anyway. :)
