### ISSUE TITLE
Unable to connect to Xerox WorkCentre 6515DN MFP

### ISSUE THREAD

**Issue by ghost** [attah/harbour-seaprint#44]
I'm trying to set up seaprint with my printer. It does not discover it, so I went to the 'Add by url' screen. I've tried all the uri's that make sense. The printer is configured on my linux laptop with cups as `ipps://10.1.3.5:631/ipp/print`. I've tried various uri's in seaprint (ipp, ipps, http, https), but for all the dialog would keep showing 'No printer found'.

It seems my printer does not like the ipp request, as seen in the logs attached. For simplicity, I tried `http://10.1.3.5/ipp/print`. Just to be sure that the printer is happy to accept ipp requests on that uri, I checked with ipptool from my linux box:

```
gmc@coltrane:~$ ipptool -t http://10.1.3.5/ipp/print /usr/share/cups/ipptool/get-printer-attributes.test
"/usr/share/cups/ipptool/get-printer-attributes.test":
    Get printer attributes using Get-Printer-Attributes                  [PASS]
gmc@coltrane:~$ 
```

Output from `harbour-seaprint`:

[seaprint.log](https://github.com/attah/harbour-seaprint/files/5661871/seaprint.log)

tcpdump from the sailfish phone when using harbour-seaprint:

[seaprint.pcap.gz](https://github.com/attah/harbour-seaprint/files/5661891/seaprint.pcap.gz)

And a successful interaction with ipptool on the laptop:

[ipptool.pcap.gz](https://github.com/attah/harbour-seaprint/files/5661904/ipptool.pcap.gz)

**Comment by attah** [comment]
Technically it is discovered, but getting its attributes fails.... but that looks the same to the user.
Wireshark isn't dissecting those log properly for whatever reason, but i see one difference already without augmentation.
Maybe your printer is more strict that is technically allowed in what "Accept-Encoding" in can serve up.

Does this make it work?
[harbour-seaprint-0.7.0+accept.identity.20201209190415.70457d5-1.armv7hl.rpm.tar.gz](https://github.com/attah/harbour-seaprint/files/5668134/harbour-seaprint-0.7.0%2Baccept.identity.20201209190415.70457d5-1.armv7hl.rpm.tar.gz)

Sorry about the extra .tar.gz, GitHub wouldn't let me attach it otherwise.

**Comment by ghost** [comment]
Odd, I did have a look at the pcap's with wireshark, and could see the POST and the response. Anyway, the version you provided in this ticket indeed shows the printer, and I managed to print a pdf, so I'd say that makes it work just fine!

I think that adding identity explicitly to the Accept-Encoding header is required if the server (the printer in this case) does not support compressing the response, otherwise there will be no encoding in common between client and server, and the server must respond with unacceptable.

Thanks for checking, hopefully this is something you can add to a future release.

**Comment by attah** [comment]
Yes, that much i see, but the IPP decoding that Wireshark has fails to engage here.
Good that it helped - now i just need to figure out how to properly put that in to an official release without accidentally breaking something else.

No, in fact the printer may not respond with unacceptable unless the client _forbids_ identity encoding.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding

I have never seen a printer or CUPS instance actually compress these answers, so only identity might be they way to go.
I'll think about it for a while and see what i land on, but your slightly pedantic printer should be easy to accommodate going forward.

**Comment by ghost** [comment]
Actually, indeed, the printer is incorrectly handling the acceptable encodings, if identity is not explicitly forbidden (which it is not by seaprint), the server may never respond with a 406 (was just reading the same page while you posted that :) )

**Comment by ghost** [comment]
Just a thought, perhaps, if you get a 406, retry with the identity explicitly added, and mark the printer as pedantic. That won't change the behaviour for well-behaving printers, but works around broken printers.

**Comment by attah** [comment]
Hmm, sounds like too much logic (that i'll end up breaking by mistake :). 
The issue i'm trying to not trip over is that Qt seems to handle decompression, but only if supported in the build/OS, and then supply decompressed data to the client. So Qt controls this header attribute to match that... meaning that overriding to compression and identity might have interesting effects. 

But only identity _should_ work... need to think about it some more, and test my printers.

**Comment by attah** [comment]
My printers have no issues with the workaround, so i'm releasing it.
