### ISSUE TITLE
Wrong version number is displayed

### ISSUE THREAD

**Issue by wheelseal** [attah/harbour-seaprint#53]
On My XA2 Seaprint don´t show the correct version number. I´ve installed version 1.0.1 from Jolla store. But in the About page I See Seaprint v1.0. A little bug but confusing.

**Comment by attah** [comment]
This was a build config problem. Reverted to the old config, so the next version will be correct again.
One of the perils of never using a released version myself...

**Comment by wheelseal** [comment]
Ok thank you.

Am Sonntag, 19. Dezember 2021 schrieb attah:
> This was a build config problem. Reverted to the old config, so the next version will be correct again.
> One of the perils of never using a released version myself...
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/attah/harbour-seaprint/issues/53#issuecomment-997412416
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***

-- 
Mit freundlichen Grüßen 

Sebastian Kergaßner

**Comment by wheelseal** [comment]
Hi, i try to override the Firmware in the override file because point 'firmware ' in Seaprint is empty. I don't find it in the debug log. Can you help me please?

**Comment by attah** [comment]
That is completely pointless to do, so i will not spend time on it.
You can always compare with other logs from the forum thread.
