### ISSUE TITLE
Missing translation license

### ISSUE THREAD

**Issue by comradekingu** [attah/harbour-seaprint#55]
"GPLv3 or later" can be added in https://hosted.weblate.org/settings/seaprint/ui-strings

**Comment by attah** [comment]
Thanks for the hint!
Still can't figure out how i was supposed to get to that page from the GUI. :(
And there is still a mountain of faff left to do according to Weblate, and the instructions are completely useless.
I have no clue what a Repository push URL is, and they don't see fit to tell me, just obvious crap like "Repository URL used for pushing.", let alone where to find it.

**Comment by comradekingu** [comment]
@attah
It leaves something to be desired.
I can try to fix it if you add "kingu" in https://hosted.weblate.org/access/seaprint/#users
Usually I look at the other components I mange to figure it out :)

**Comment by attah** [comment]
Thank you, very nice of you!
I have now done so.

**Comment by attah** [comment]
Another observation is the it seems unable to take the source text as input.
The unsuffixed file (the template) is treated as English, and that emptiness is what you see for other languages.
For English, it has mangled the source strings with a scope prefix :(
I very much do not feel like going to translation ids.

Surely there must be a setting for this.... but once again i find myself only finding useless settings.

**Comment by comradekingu** [comment]
@attah Maybe  #61?
Or "development (generated) development" as locale, perhaps the style at the bottom of
https://hosted.weblate.org/settings/seaprint/ui-strings/#files but that seems unlikely given the other languages work.

**Comment by attah** [comment]
"Source language can not be changed, please recreate the component instead."
They are indeed doing a great job driving me up a wall.

**Comment by comradekingu** [comment]
@attah 
Every new configuration is a work that cannot be replicated. Provocation is as we all know the modern art.
Did it work for the source language with #61? Now it doesn't work for anything, which is somehow consistent.

Edit: https://gitlab.com/ilpianista/harbour-SailHN/-/blob/master/translations/harbour-sailhn.ts has line numbers, maybe that will do it? https://hosted.weblate.org/projects/harbour-sailhn/#components

**Comment by attah** [comment]
It did not work... i tried re-creating the whatever they call the actual translations a few times with different "development" languages as source. No dice.
I contacted the support, but i don't expect much.

**Comment by attah** [comment]
I give up.
Finally they told me what was wrong with the project config - it was set up to be monolingual when it is in fact bilingual.
Yeah, i know... neither of these terms actually mean anything for project config without a lot of specialty knowledge.
What it _really_ means is that the field for "Monolingual base language file" should be left empty when the "keys" are the source language.

Weblate is just way too much faff to configure - there are dozens and dozens of settings, all looking equally important and disorganized. The checklist basically screaming at me to add stuff that is not needed also doesn't help.
So while the config worked, i I just can't imagine having to deal with it regularly.

**Comment by comradekingu** [comment]
@attah Sorry about getting it wrong.
Dealing with it regularly isn't touching any of those settings luckily.
The checklist isn't to do with Weblate, but rather the "Hosted" service.
https://weblate.bubu1.eu/ has none of that for example, which is why I recommend it over Hosted.
