### ISSUE TITLE
Crash with jpeg files on Brother HL-L 8260CDW

### ISSUE THREAD

**Issue by mipstux** [attah/harbour-seaprint#66]
Hello
Impossible to print a picture in jpeg format. I hav no trobles with png or pdf files. This printer is in our local network and we used IPP protocol.
So i launch SeaPrint with a terminal and her all the sequence since i open the app and launch the jpeg print.

My smartphone is a X10ii. I remember that with old version with SeaPrint i had no crash.
We have the same crash with the XA2 of my wife
[crash_of_seaprint_with_jpeg_on_Brother_HL-L8260CDW.txt](https://github.com/attah/harbour-seaprint/files/8805335/crash_of_seaprint_with_jpeg_on_Brother_HL-L8260CDW.txt)
.
Thanks in advance and sorry for my not very fluent english ;-)

**Comment by attah** [comment]
Very strange indeed... Not sure how i missed that. But looks like an easy fix - but probably not something i have time for today.

**Comment by attah** [comment]
This should do it: https://github.com/attah/harbour-seaprint/releases/tag/1.1.4
Thanks for your report!
