### ISSUE TITLE
Cannot print to Lexmark cs310dn

### ISSUE THREAD

**Issue by madsci** [attah/harbour-seaprint#79]
Hi
I cannot print anymore to my Lexmark cs310dn laser printer. I a previous version (presumably 1.2) it was working.

The printer prints an empty sheet with following error
"PDF Error 16: PostScript Error: SYNTAXERROR"

I tried more than one different document. Printing from linux is fine.

**Comment by attah** [comment]
Hi!
I tested on my cs410n, which should be fairly similar, but it worked fine.
The different documents you tried were not all from the same source, right?
(I.e. will not be broken in the same way, if that is what you are hitting)
I also assume they open fine in sailfish-office?

Could you also please send me the printer debug info (rapidly tap printer 5 times with no document selected). This way i can double-check the settings logic against your printer even if i don't have it here.

I can't immediately see anything in the 1.3-series that even touches this area; but it would be helpful if you found the latest working version.
Old releases can be found here https://github.com/attah/harbour-seaprint/releases

As a workaround (should you need to print quickly), and further narrowing-down of the issue; you can manually select the format the document will be transferred as (if PDF was available, that will have been preferred for auto-detect). The raster formats will not have this exact issue at least, and it's not super clear if it was PDF or Postscript that failed either.

**Comment by madsci** [comment]
Thank you for your reply.

Yes, at least 3 pdf docs from different sources fail. On the pc, they open fine also in sailfish documents viewer.

After changing the print format, 'ps' is printing fine. Neither 'auto detect' nor 'pdf' prints the page.

I will try to install older versions to narrow down the issue. In the meantime, here is my config:

{
  "charset-configured": {
    "tag": 71,
    "value": "utf-8"
  },
  "charset-supported": {
    "tag": 71,
    "value": [
      "utf-8"
    ]
  },
  "color-supported": {
    "tag": 34,
    "value": true
  },
  "compression-supported": {
    "tag": 68,
    "value": [
      "none",
      "gzip"
    ]
  },
  "copies-default": {
    "tag": 33,
    "value": 1
  },
  "copies-supported": {
    "tag": 51,
    "value": {
      "high": 999,
      "low": 1
    }
  },
  "device-service-count": {
    "tag": 33,
    "value": 1
  },
  "device-uuid": {
    "tag": 69,
    "value": "urn:uuid:e2d46294-263f-4d3c-8afa-7ebfee07af09"
  },
  "document-format-default": {
    "tag": 73,
    "value": "application/octet-stream"
  },
  "document-format-preferred": {
    "tag": 73,
    "value": "application/pdf"
  },
  "document-format-supported": {
    "tag": 73,
    "value": [
      "application/octet-stream",
      "image/urf",
      "image/pwg-raster",
      "application/pdf",
      "image/jpeg",
      "application/postscript",
      "application/vnd.hp-PCL",
      "text/plain"
    ]
  },
  "document-format-varying-attributes": {
    "tag": 68,
    "value": "copies-supported"
  },
  "document-password-supported": {
    "tag": 33,
    "value": [
      0
    ]
  },
  "finishings-default": {
    "tag": 35,
    "value": 3
  },
  "finishings-supported": {
    "tag": 35,
    "value": [
      3
    ]
  },
  "generated-natural-language-supported": {
    "tag": 72,
    "value": [
      "en-us"
    ]
  },
  "identify-actions-default": {
    "tag": 68,
    "value": "display"
  },
  "identify-actions-supported": {
    "tag": 68,
    "value": [
      "display",
      "sound"
    ]
  },
  "ipp-features-supported": {
    "tag": 68,
    "value": [
      "airprint-1.5",
      "wfds-print-1.0"
    ]
  },
  "ipp-versions-supported": {
    "tag": 68,
    "value": [
      "1.0",
      "1.1",
      "2.0"
    ]
  },
  "job-constraints-supported": {
    "tag": 52,
    "value": [
      {
        "media-col": {
          "tag": 52,
          "value": {
            "media-type": {
              "tag": 68,
              "value": "transparency"
            }
          }
        },
        "resolver-name": {
          "tag": 66,
          "value": "duplex_transparency"
        },
        "sides": {
          "tag": 68,
          "value": [
            "two-sided-long-edge",
            "two-sided-short-edge"
          ]
        }
      }
    ]
  },
  "job-creation-attributes-supported": {
    "tag": 68,
    "value": [
      "compression-supplied",
      "copies",
      "date-time-at-completed",
      "date-time-at-creation",
      "date-time-at-processing",
      "document-format-supplied",
      "document-format-version",
      "document-format-version-supplied",
      "document-name-supplied",
      "finishings",
      "ipp-attribute-fidelity",
      "job-description",
      "job-id",
      "job-ids",
      "job-impressions",
      "job-impressions-completed",
      "job-k-octets-processed",
      "job-media-sheets",
      "job-media-sheets-completed",
      "job-name",
      "job-originating-user-name",
      "job-originating-user-uri",
      "job-pages",
      "job-pages-completed",
      "job-pages-completed-current-copy",
      "job-pages-per-set",
      "job-printer-up-time",
      "job-printer-uri",
      "job-sheets",
      "job-state",
      "job-state-reasons",
      "job-state-message",
      "job-template",
      "job-uri",
      "job-uuid",
      "lexmark.com-debug",
      "media",
      "media-bottom-margin",
      "media-col",
      "media-left-margin",
      "media-right-margin",
      "media-source",
      "media-top-margin",
      "media-type",
      "multiple-document-handling",
      "number-up",
      "orientation-requested",
      "output-bin",
      "output-mode",
      "page-ranges",
      "print-color-mode",
      "print-content-optimize",
      "print-quality",
      "print-scaling",
      "printer-resolution",
      "sides",
      "time-at-completed",
      "time-at-creation",
      "time-at-processing"
    ]
  },
  "job-ids-supported": {
    "tag": 34,
    "value": true
  },
  "job-impressions-supported": {
    "tag": 51,
    "value": {
      "high": 2147483647,
      "low": 1
    }
  },
  "job-media-sheets-supported": {
    "tag": 51,
    "value": {
      "high": 2147483647,
      "low": 1
    }
  },
  "job-pages-per-set-supported": {
    "tag": 34,
    "value": false
  },
  "job-resolvers-supported": {
    "tag": 52,
    "value": [
      {
        "media-col": {
          "tag": 52,
          "value": {
            "media-type": {
              "tag": 68,
              "value": "stationery"
            }
          }
        },
        "resolver-name": {
          "tag": 66,
          "value": "duplex_transparency"
        },
        "sides": {
          "tag": 68,
          "value": "one-sided"
        }
      }
    ]
  },
  "job-sheets-default": {
    "tag": 68,
    "value": "none"
  },
  "job-sheets-supported": {
    "tag": 68,
    "value": [
      "none",
      "standard"
    ]
  },
  "jpeg-k-octets-supported": {
    "tag": 51,
    "value": {
      "high": 196608,
      "low": 0
    }
  },
  "jpeg-x-dimension-supported": {
    "tag": 51,
    "value": {
      "high": 32768,
      "low": 1
    }
  },
  "jpeg-y-dimension-supported": {
    "tag": 51,
    "value": {
      "high": 32768,
      "low": 1
    }
  },
  "landscape-orientation-requested-preferred": {
    "tag": 35,
    "value": 4
  },
  "marker-colors": {
    "tag": 66,
    "value": [
      "#00FFFF",
      "#FF00FF",
      "#FFFF00",
      "#000000"
    ]
  },
  "marker-high-levels": {
    "tag": 33,
    "value": [
      100,
      100,
      100,
      100
    ]
  },
  "marker-levels": {
    "tag": 33,
    "value": [
      30,
      100,
      50,
      90
    ]
  },
  "marker-low-levels": {
    "tag": 33,
    "value": [
      21,
      21,
      21,
      21
    ]
  },
  "marker-names": {
    "tag": 66,
    "value": [
      "Cyan",
      "Magenta",
      "Yellow",
      "Black"
    ]
  },
  "marker-types": {
    "tag": 68,
    "value": [
      "toner-cartridge",
      "toner-cartridge",
      "toner-cartridge",
      "toner-cartridge"
    ]
  },
  "media-bottom-margin-default": {
    "tag": 33,
    "value": 423
  },
  "media-bottom-margin-supported": {
    "tag": 33,
    "value": [
      423
    ]
  },
  "media-col-default": {
    "tag": 52,
    "value": {
      "media-bottom-margin": {
        "tag": 33,
        "value": 423
      },
      "media-left-margin": {
        "tag": 33,
        "value": 423
      },
      "media-right-margin": {
        "tag": 33,
        "value": 423
      },
      "media-size": {
        "tag": 52,
        "value": {
          "x-dimension": {
            "tag": 33,
            "value": 21000
          },
          "y-dimension": {
            "tag": 33,
            "value": 29700
          }
        }
      },
      "media-source": {
        "tag": 68,
        "value": "tray-1"
      },
      "media-top-margin": {
        "tag": 33,
        "value": 423
      },
      "media-type": {
        "tag": 68,
        "value": "stationery-lightweight"
      }
    }
  },
  "media-col-ready": {
    "tag": 52,
    "value": {
      "media-bottom-margin": {
        "tag": 33,
        "value": 423
      },
      "media-left-margin": {
        "tag": 33,
        "value": 423
      },
      "media-right-margin": {
        "tag": 33,
        "value": 423
      },
      "media-size": {
        "tag": 52,
        "value": {
          "x-dimension": {
            "tag": 33,
            "value": 21000
          },
          "y-dimension": {
            "tag": 33,
            "value": 29700
          }
        }
      },
      "media-source": {
        "tag": 68,
        "value": "tray-1"
      },
      "media-top-margin": {
        "tag": 33,
        "value": 423
      },
      "media-type": {
        "tag": 68,
        "value": "stationery-lightweight"
      }
    }
  },
  "media-col-supported": {
    "tag": 68,
    "value": [
      "media-size",
      "media-top-margin",
      "media-bottom-margin",
      "media-left-margin",
      "media-right-margin",
      "media-source",
      "media-type"
    ]
  },
  "media-default": {
    "tag": 68,
    "value": "iso_a4_210x297mm"
  },
  "media-left-margin-default": {
    "tag": 33,
    "value": 423
  },
  "media-left-margin-supported": {
    "tag": 33,
    "value": [
      423
    ]
  },
  "media-ready": {
    "tag": 68,
    "value": [
      "iso_a4_210x297mm"
    ]
  },
  "media-right-margin-default": {
    "tag": 33,
    "value": 423
  },
  "media-right-margin-supported": {
    "tag": 33,
    "value": [
      423
    ]
  },
  "media-size-supported": {
    "tag": 52,
    "value": [
      [
        {
          "x-dimension": {
            "tag": 33,
            "value": 9842
          },
          "y-dimension": {
            "tag": 33,
            "value": 19050
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 9842
          },
          "y-dimension": {
            "tag": 33,
            "value": 22542
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 10477
          },
          "y-dimension": {
            "tag": 33,
            "value": 24130
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 17600
          },
          "y-dimension": {
            "tag": 33,
            "value": 25000
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 16200
          },
          "y-dimension": {
            "tag": 33,
            "value": 22900
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 11000
          },
          "y-dimension": {
            "tag": 33,
            "value": 22000
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 21590
          },
          "y-dimension": {
            "tag": 33,
            "value": 27940
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 18200
          },
          "y-dimension": {
            "tag": 33,
            "value": 25700
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 21000
          },
          "y-dimension": {
            "tag": 33,
            "value": 29700
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 14800
          },
          "y-dimension": {
            "tag": 33,
            "value": 21000
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 21590
          },
          "y-dimension": {
            "tag": 33,
            "value": 33020
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 13970
          },
          "y-dimension": {
            "tag": 33,
            "value": 21590
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 21590
          },
          "y-dimension": {
            "tag": 33,
            "value": 34036
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 10500
          },
          "y-dimension": {
            "tag": 33,
            "value": 14800
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 21600
          },
          "y-dimension": {
            "tag": 33,
            "value": 35600
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 21590
          },
          "y-dimension": {
            "tag": 33,
            "value": 35560
          }
        },
        {
          "x-dimension": {
            "tag": 33,
            "value": 18415
          },
          "y-dimension": {
            "tag": 33,
            "value": 26670
          }
        },
        {
          "x-dimension": {
            "tag": 51,
            "value": {
              "high": 29692,
              "low": 9855
            }
          },
          "y-dimension": {
            "tag": 51,
            "value": {
              "high": 43180,
              "low": 14808
            }
          }
        }
      ]
    ]
  },
  "media-source-default": {
    "tag": 68,
    "value": "tray-1"
  },
  "media-source-supported": {
    "tag": 68,
    "value": [
      "auto",
      "envelope",
      "manual",
      "tray-1"
    ]
  },
  "media-supported": {
    "tag": 68,
    "value": [
      "na_monarch_3.875x7.5in",
      "na_number-9_3.875x8.875in",
      "na_number-10_4.125x9.5in",
      "iso_b5_176x250mm",
      "iso_c5_162x229mm",
      "iso_dl_110x220mm",
      "na_letter_8.5x11in",
      "jis_b5_182x257mm",
      "iso_a4_210x297mm",
      "iso_a5_148x210mm",
      "na_foolscap_8.5x13in",
      "na_invoice_5.5x8.5in",
      "na_oficio_8.5x13.4in",
      "iso_a6_105x148mm",
      "om_universal_216x356mm",
      "na_legal_8.5x14in",
      "na_executive_7.25x10.5in",
      "custom_min_98.55x148.08mm",
      "custom_max_296.92x431.8mm"
    ]
  },
  "media-top-margin-default": {
    "tag": 33,
    "value": 423
  },
  "media-top-margin-supported": {
    "tag": 33,
    "value": [
      423
    ]
  },
  "media-type-default": {
    "tag": 68,
    "value": "stationery-lightweight"
  },
  "media-type-supported": {
    "tag": 68,
    "value": [
      "envelope",
      "custom-media-type-customtype1",
      "custom-media-type-customtype2",
      "custom-media-type-customtype3",
      "custom-media-type-customtype4",
      "custom-media-type-customtype5",
      "custom-media-type-customtype6",
      "stationery",
      "cardstock",
      "transparency",
      "custom-media-type-recycled",
      "custom-media-type-glossy",
      "labels",
      "custom-media-type-bond",
      "stationery-letterhead",
      "stationery-preprinted",
      "custom-media-type-coloredpaper",
      "stationery-lightweight",
      "stationery-heavyweight",
      "custom-media-type-rough"
    ]
  },
  "mopria-certified": {
    "tag": 65,
    "value": "2.0"
  },
  "multiple-document-handling-default": {
    "tag": 68,
    "value": "separate-documents-collated-copies"
  },
  "multiple-document-handling-supported": {
    "tag": 68,
    "value": [
      "separate-documents-uncollated-copies",
      "separate-documents-collated-copies"
    ]
  },
  "multiple-document-jobs-supported": {
    "tag": 34,
    "value": false
  },
  "multiple-operation-time-out": {
    "tag": 33,
    "value": 120
  },
  "multiple-operation-time-out-action": {
    "tag": 68,
    "value": "abort-job"
  },
  "natural-language-configured": {
    "tag": 72,
    "value": "en-us"
  },
  "number-up-default": {
    "tag": 33,
    "value": 1
  },
  "number-up-supported": {
    "tag": 33,
    "value": [
      1,
      2,
      3,
      4,
      6,
      9,
      12,
      16
    ]
  },
  "operations-supported": {
    "tag": 35,
    "value": [
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      16,
      17,
      18,
      57,
      59,
      60
    ]
  },
  "orientation-requested-default": {
    "tag": 35,
    "value": 3
  },
  "orientation-requested-supported": {
    "tag": 35,
    "value": [
      3,
      4,
      6,
      5,
      7
    ]
  },
  "output-bin-default": {
    "tag": 68,
    "value": "face-down"
  },
  "output-bin-supported": {
    "tag": 68,
    "value": [
      "face-down"
    ]
  },
  "output-mode-default": {
    "tag": 68,
    "value": "color"
  },
  "output-mode-supported": {
    "tag": 68,
    "value": [
      "auto",
      "monochrome",
      "auto-monochrome",
      "color"
    ]
  },
  "page-ranges-supported": {
    "tag": 34,
    "value": true
  },
  "pages-per-minute": {
    "tag": 33,
    "value": 25
  },
  "pages-per-minute-color": {
    "tag": 33,
    "value": 25
  },
  "pdf-fit-to-page": {
    "tag": 34,
    "value": true
  },
  "pdf-fit-to-page-default": {
    "tag": 34,
    "value": true
  },
  "pdf-fit-to-page-supported": {
    "tag": 34,
    "value": true
  },
  "pdf-k-octets-supported": {
    "tag": 51,
    "value": {
      "high": 132096,
      "low": 0
    }
  },
  "pdf-size-constraints": {
    "tag": 51,
    "value": {
      "high": 135266304,
      "low": 0
    }
  },
  "pdf-versions-supported": {
    "tag": 68,
    "value": [
      "iso-32000-1_2008"
    ]
  },
  "pdl-override-supported": {
    "tag": 68,
    "value": [
      "attempted"
    ]
  },
  "preferred-attributes-supported": {
    "tag": 34,
    "value": false
  },
  "print-color-mode-default": {
    "tag": 68,
    "value": "color"
  },
  "print-color-mode-supported": {
    "tag": 68,
    "value": [
      "auto",
      "monochrome",
      "auto-monochrome",
      "color"
    ]
  },
  "print-content-optimize-default": {
    "tag": 68,
    "value": "auto"
  },
  "print-content-optimize-supported": {
    "tag": 68,
    "value": [
      "auto",
      "photo",
      "graphics",
      "text",
      "text-and-graphics"
    ]
  },
  "print-quality-default": {
    "tag": 35,
    "value": 4
  },
  "print-quality-supported": {
    "tag": 35,
    "value": [
      4
    ]
  },
  "print-scaling-default": {
    "tag": 68,
    "value": "auto"
  },
  "print-scaling-supported": {
    "tag": 68,
    "value": [
      "auto",
      "auto-fit",
      "fill",
      "fit",
      "none"
    ]
  },
  "printer-alert": {
    "tag": 48,
    "value": "none"
  },
  "printer-alert-description": {
    "tag": 65,
    "value": "none"
  },
  "printer-config-change-date-time": {
    "tag": 49,
    "value": "2023-06-07T22:32:49+02:00"
  },
  "printer-config-change-time": {
    "tag": 33,
    "value": 56
  },
  "printer-current-time": {
    "tag": 49,
    "value": "2023-06-07T22:43:44+02:00"
  },
  "printer-device-id": {
    "tag": 65,
    "value": "MANUFACTURER:Lexmark;COMMAND SET:PCL 6 Emulation, PostScript Level 3 Emulation, PDF, URF, PWG, NPAP, PJL;MODEL:Lexmark CS310 Series;CLS:PRINTER;DES:Lexmark CS310dn;CID:LexmarkPrinterColorA;COMMENT:ECP1.0, LV_043D, LP_022E, LF_008C;"
  },
  "printer-dns-sd-name": {
    "tag": 66,
    "value": "Lexmark CS310dn"
  },
  "printer-firmware-name": {
    "tag": 66,
    "value": [
      "IPP",
      "JPEG",
      "PDF",
      "URF",
      "FirmwareVersion"
    ]
  },
  "printer-firmware-string-version": {
    "tag": 65,
    "value": [
      "2.0",
      "1.02",
      "1.7",
      "1.4",
      "LW80.VYL.P235-0"
    ]
  },
  "printer-firmware-version": {
    "tag": 48,
    "value": [
      "<0200>",
      "<0102>",
      "<0170>",
      "<0140>",
      "LW80.VYL.P235-0"
    ]
  },
  "printer-geo-location": {
    "tag": 18,
    "value": ""
  },
  "printer-get-attributes-supported": {
    "tag": 68,
    "value": [
      "all",
      "attributes-charset",
      "attributes-natural-language",
      "compression",
      "copies",
      "document-format",
      "document-name",
      "document-natural-language",
      "document-uri",
      "finishings",
      "identify-actions",
      "job-originating-user",
      "job-pages-per-set",
      "job-sheets",
      "job-template",
      "last-document",
      "lexmark.com-debug",
      "lexmark.com-document-format",
      "limit",
      "media",
      "media-bottom-margin",
      "media-col",
      "media-left-margin",
      "media-right-margin",
      "media-source",
      "media-top-margin",
      "media-type",
      "message",
      "multiple-document-handling",
      "my-jobs",
      "number-up",
      "orientation-requested",
      "output-bin",
      "output-mode",
      "page-ranges",
      "print-color-mode",
      "print-content-optimize",
      "print-quality",
      "print-scaling",
      "printer-resolution",
      "printer-uri",
      "requested-attributes",
      "requesting-user-name",
      "requesting-user-uri",
      "sides",
      "which-jobs"
    ]
  },
  "printer-icons": {
    "tag": 69,
    "value": [
      "https://192.168.11.11:443/cgi-bin/dynamic/printer/images/printer.48x48.png",
      "https://192.168.11.11:443/cgi-bin/dynamic/printer/images/printer.128x128.png",
      "https://192.168.11.11:443/cgi-bin/dynamic/printer/images/printer.512x512.png"
    ]
  },
  "printer-info": {
    "tag": 65,
    "value": "Color - Up to 25 Pages/Minute"
  },
  "printer-input-tray": {
    "tag": 48,
    "value": [
      "name=auto;type=other;dimunit=micrometers;mediafeed=297000;mediaxfeed=210000;unit=sheets;maxcapacity=250;level=-3;status=0;",
      "name=envelope;type=sheetFeedManual;dimunit=micrometers;mediafeed=190500;mediaxfeed=98420;unit=sheets;maxcapacity=1;level=-3;status=0;",
      "name=manual;type=sheetFeedManual;dimunit=micrometers;mediafeed=297000;mediaxfeed=210000;unit=sheets;maxcapacity=1;level=-3;status=0;",
      "name=tray-1;type=sheetFeedAutoNonRemovableTray;dimunit=micrometers;mediafeed=297000;mediaxfeed=210000;unit=sheets;maxcapacity=250;level=-3;status=0;"
    ]
  },
  "printer-is-accepting-jobs": {
    "tag": 34,
    "value": true
  },
  "printer-kind": {
    "tag": 68,
    "value": [
      "document",
      "envelope",
      "label"
    ]
  },
  "printer-location": {
    "tag": 65,
    "value": ""
  },
  "printer-make-and-model": {
    "tag": 65,
    "value": "Lexmark CS310dn"
  },
  "printer-more-info": {
    "tag": 69,
    "value": "https://192.168.11.11:443/cgi-bin/dynamic/config/net/airprint.html"
  },
  "printer-name": {
    "tag": 66,
    "value": "Lexmark CS310dn"
  },
  "printer-organization": {
    "tag": 65,
    "value": "no-value"
  },
  "printer-organizational-unit": {
    "tag": 65,
    "value": "no-value"
  },
  "printer-output-tray": {
    "tag": 48,
    "value": "name=face-down;type=unRemovableBin;unit=sheets;maxcapacity=125;remaining=-3;status=0;stackingorder=firstToLast;pagedelivery=faceDown;"
  },
  "printer-resolution-default": {
    "tag": 50,
    "value": {
      "units": 3,
      "x": 600,
      "y": 600
    }
  },
  "printer-resolution-supported": {
    "tag": 50,
    "value": [
      {
        "units": 3,
        "x": 300,
        "y": 300
      },
      {
        "units": 3,
        "x": 600,
        "y": 600
      },
      {
        "units": 3,
        "x": 1200,
        "y": 1200
      }
    ]
  },
  "printer-state": {
    "tag": 35,
    "value": 3
  },
  "printer-state-change-date-time": {
    "tag": 49,
    "value": "2023-06-07T22:42:59+02:00"
  },
  "printer-state-change-time": {
    "tag": 33,
    "value": 664
  },
  "printer-state-message": {
    "tag": 65,
    "value": "Printer is idle."
  },
  "printer-state-reasons": {
    "tag": 68,
    "value": [
      "none"
    ]
  },
  "printer-supplies-info-uri": {
    "tag": 69,
    "value": "https://192.168.11.11:443/"
  },
  "printer-supply-info-uri": {
    "tag": 69,
    "value": "https://192.168.11.11:443/"
  },
  "printer-up-time": {
    "tag": 33,
    "value": 709
  },
  "printer-uri-supported": {
    "tag": 69,
    "value": [
      "ipp://192.168.11.11:631/ipp/print",
      "ipps://192.168.11.11:443/ipp/print"
    ]
  },
  "printer-uuid": {
    "tag": 69,
    "value": "urn:uuid:e2d46294-263f-4d3c-8afa-7ebfee07af09"
  },
  "pwg-raster-document-resolution-supported": {
    "tag": 50,
    "value": [
      {
        "units": 3,
        "x": 300,
        "y": 300
      },
      {
        "units": 3,
        "x": 600,
        "y": 600
      }
    ]
  },
  "pwg-raster-document-sheet-back": {
    "tag": 68,
    "value": "normal"
  },
  "pwg-raster-document-type-supported": {
    "tag": 68,
    "value": [
      "black_1",
      "black_8",
      "srgb_8"
    ]
  },
  "queued-job-count": {
    "tag": 33,
    "value": 0
  },
  "reference-uri-schemes-supported": {
    "tag": 70,
    "value": [
      "http",
      "https",
      "ftp"
    ]
  },
  "requesting-user-uri-supported": {
    "tag": 34,
    "value": true
  },
  "sides-default": {
    "tag": 68,
    "value": "two-sided-long-edge"
  },
  "sides-supported": {
    "tag": 68,
    "value": [
      "one-sided",
      "two-sided-long-edge",
      "two-sided-short-edge"
    ]
  },
  "urf-supported": {
    "tag": 68,
    "value": [
      "V1.4",
      "CP1",
      "PQ4",
      "W8",
      "MT1-2-3-4-5-6-8-10-11-12-13",
      "RS300-600",
      "SRGB24",
      "DM1",
      "OB10",
      "IS5-4-20",
      "IFU20",
      "FN3"
    ]
  },
  "uri-authentication-supported": {
    "tag": 68,
    "value": [
      "none",
      "none"
    ]
  },
  "uri-security-supported": {
    "tag": 68,
    "value": [
      "none",
      "tls"
    ]
  },
  "which-jobs-supported": {
    "tag": 68,
    "value": [
      "completed",
      "not-completed"
    ]
  }
}

**Comment by attah** [comment]
There shouldn't (tm) be anything significant that could be done different, basically all the way back to 1.0. But if you do find anything that will be highly interesting. Auto-detect will select PDF if available, so that makes sense. From the debug info i see that PDF is advertised properly, and not deduced. So it should be something that can be trusted to work, and SeaPrint will also have told the printer what to expect, at least when you explicitly selected it. So that should rule out auto-detect issues on the printer side.

**Comment by madsci** [comment]
Hi attah
While trying out the previous versions - all working properly - I ended up at the latest 1.3.1. Surprisingly this is working too. Obviously, something was wrong with my initial installation :-(
Thank you for your help and I am glad it works again like a charm!
Cheers
