### ISSUE TITLE
Problems whith Brother MFC-J5320DW

### ISSUE THREAD

**Issue by Tux81** [attah/harbour-seaprint#82]
Hello! My printer (Brother MFC-J5320DW) is displayed in the app and I can also select a document and send it to the printer. The printer even shows on the display that it is receiving data, but then prints nothing and shows no further reaction. What could be the problem?

**Comment by attah** [comment]
Something along the lines of bad format auto-detect, or not actually supporting a format that it claims to perhaps.
Try actually selecting a transfer format (and try them all).

Also please post the debug output obtained by tapping the printer 5 times with no document selected.

**Comment by Tux81** [comment]
[debug.txt](https://github.com/attah/harbour-seaprint/files/14351377/debug.txt)

**Comment by attah** [comment]
How did selecting formats go?
Nothing obviously strange with the formats in the debug info.
What about another document or a picture?

**Comment by Tux81** [comment]
I have now selected a PDF document for printing and set PWG-Raster as the Transfair format. Now it suddenly works. Thank you very much!

**Comment by attah** [comment]
So was it an input format problem (which one), or a transfer-format problem?

**Comment by Tux81** [comment]
I think it must have been the Transfair format. I have now tried pdf files, odt files and jpg files. It always works with the pwg raster setting.

**Comment by attah** [comment]
...and it stops working if you set it to auto?

**Comment by Tux81** [comment]
Yes!

**Comment by attah** [comment]
There we have it then. SeaPrint will have produced PWG raster for that printer regardless; but also have explicitly told it when you make the selection.

**Comment by Tux81** [comment]
Thanks again for the help. It's great that I can now use the app. I had it installed for a very long time. It just never worked until now
