### ISSUE TITLE
Idea of a change in the Printer-Properties page

### ISSUE THREAD

**Issue by wheelseal** [attah/harbour-seaprint#84]
I have a Idea for the Printer-Properties page:

The Printer name is shown next to the headline. My Idea is to move in before "Make and model". Take a look (Please ignore the false font :) ):

Before

![idea printername 1](https://github.com/attah/harbour-seaprint/assets/61382908/d3f65c2f-cce4-42ae-b2c0-bd696d3e88fc)

After
![idea printername 2](https://github.com/attah/harbour-seaprint/assets/61382908/9c290e08-651e-4c31-8fda-624f6dad7fa2)

hat do you mean about that?

**Comment by attah** [comment]
I don't see the point. If anything, i should switch the header and subheader around to be more like the other pages.
